name: Deploy dev to beanstalk
on:
    push:
      branches:
        - dev
jobs:
    deploy:
      environment: dev-deployment
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Use Node.js 18
          uses: actions/setup-node@v1
          with:
              node-version: 18.18.0

        - name: install dependencies
          env:
            NODE_OPTIONS: --openssl-legacy-provider
          run: |
                npm run install-all

        - name: build
          env:
            NODE_OPTIONS: --openssl-legacy-provider
          run: |
                npm run build            

        - name: Deploy to AWS Elastic Beanstalk
          uses: einaregilsson/beanstalk-deploy@v15
          with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              application_name: ${{ vars.EB_APP_NAME }}
              environment_name: ${{ vars.EB_ENV_NAME }}
              version_label: ${{ github.sha }}
              region: ${{ vars.AWS_REGION }}
              wait_for_deployment: true

