name: Deploy dev to beanstalk
on:
    push:
      branches:
        - dev
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Deploy to AWS Elastic Beanstalk
          uses: einaregilsson/beanstalk-deploy@v15
          with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              application_name: ${{ vars.EB_APP_NAME }}
              environment_name: ${{ vars.EB_ENV_NAME }}
              version_label: ${{ github.sha }}
              region: ${{ vars.AWS_REGION }}
              wait_for_deployment: true

