name: Deploy dev to beanstalk
on:
    push:
      branches:
        - dev
jobs:
    deploy:
      environment: dev-deployment
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Use Node.js 18
          uses: actions/setup-node@v1
          with:
              node-version: 18.18.0

        - name: cache node modules
          uses: actions/cache@v2
          with:
              path: node_modules
              key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

        - name: install dependencies
          env:
            NODE_OPTIONS: --openssl-legacy-provider
          run: |
                npm run install-all

        - name: build
          env:
            NODE_OPTIONS: --openssl-legacy-provider
            CI: false
          run: |
                npm run build            

        - name: install python3
          uses: actions/setup-python@v2
          with:
              python-version: 3.8
        - name: Install pip
          run: |
                python -m pip install --upgrade pip

        - name: Install Elastic Beanstalk CLI
          run: |
                pip install awsebcli --upgrade --user

        - name: Use eb cli to deploy to Elastic Beanstalk
          run: |
                eb deploy ${{ vars.EB_ENV_NAME }} --region ${{ vars.AWS_REGION }}

